apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mercury
spec:
  replicas: 1
  selector:
    matchLabels:
      name: Mercury
  template:
    metadata:
      labels:
        name: Mercury
    spec:
      containers:
        - name: Mercury
          image: "{{IMAGE}}"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "20"]
          resources:
            requests:
              cpu: 0.1
              memory: 100Mi
            limits:
              cpu: 0.5
              memory: 200Mi
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /    # application health check API endpoint
              port: 80   # container port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /    # application health check API endpoint
              port: 80   # container port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
